name: Main

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  linux:
    name: Linux Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World!
        run: echo "Hello World!"

  windows:
    name: Windows Job
    runs-on: windows-latest
    steps:
      - name: Print Hello World!
        run: echo "Hello World!"

  macos:
    name: macOS Job
    runs-on: macos-latest
    steps:
      - name: Print Hello World!
        run: echo "Hello World!"

  final:
    name: Final Job
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Print Finalizado!
        run: echo "Finalizado!"
